name: Run Jest Tests

on:
  pull_request:
    branches:
      - main  # Change this if your default branch is different

jobs:
  test:
    runs-on: ubuntu-latest  # Runs on the latest Ubuntu environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Checks out your code

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Adjust to your project's Node.js version

      - name: Install dependencies
        run: npm install  # Or yarn install, depending on your setup

      - name: Run Jest tests
        run: npm test  # Or "yarn test" if you're using Yarn
